### PR TITLE
PISTON-1227 add additional check to is_owner function

### PR DESCRIPTION
**Pull request by alexey-khabulyak**
In case of "call forwarding" a caller gets full access to a callee VM.
For example.
Extension 1000 enables CallForwarding to 1000. If someone calls 1000, kazoo makes call transfer from 1000 to 1000.
It responds with "stop calling your self...stop calling your self" and returns 0 devices.
Then kazoo starts VM application.
So Call record and VM record has the same OwnerId, and the caller hears "You have ...."
With this fix a caller leaves a message instead of listening to callee's saved messages.

4.3 PR: https://github.com/2600hz/kazoo/pull/6730

### CODE REVIEW

**Comment by lazedo** [comment]
@alexey-khabulyak did you reproduced this with this repo ? pretty sure this was already handled

**Comment by alexey-khabulyak** [comment]
> @alexey-khabulyak did you reproduced this with this repo ? pretty sure this was already handled

@lazedo hm. you are right. I can't reproduce this bug on kazoo5. Is it possible to back-port these fixes to 4.3? Or there are too many changes?

**Comment by lazedo** [comment]
@alexey-khabulyak too many changes.

**Comment by alexey-khabulyak** [comment]
@lazedo got it. thnx.

**Pull request closed without merging**
