### PR TITLE
[master] FREE-56: use sip_credentials view when searching for ringback user

### PR DESCRIPTION
**Pull request by icehess**
There is some disagreement between lower casing sip username or not. Since this impacting the park ringback functionality, changing park to use a view that lower cases sip username.

The username part of `Referred-By` is already lower case.

### CODE REVIEW

**Comment by icehess** [comment]
Required PRs:
- https://github.com/2600hz/kazoo-core/pull/600
- https://github.com/2600hz/kazoo-core/pull/603
- https://github.com/2600hz/kazoo-stepswitch/pull/39

Backport PRs:
- master: https://github.com/2600hz/kazoo-callflow/pull/177
- 5.1: https://github.com/2600hz/kazoo-callflow/pull/174
- 5.0: https://github.com/2600hz/kazoo-callflow/pull/176

**Review by lazedo — CHANGES_REQUESTED** [review]
lets talk

**Comment by icehess** [comment]
I know you don't agree with normalizing/lower casing username, but the username here is already normalized somewhere.
What do you suggest to do here?

**Comment by lazedo** [comment]
@icehess use kapps_call:restricted_endpoint_id/1 and kapps_call:endpoint_id/1 and kapps_call:authorizing_id/1 already have the values you want. 
in parking app, we use the below to set the ringback_endpoint_id when creating the slot and it doesn't need to be updated (when attended transfer is completed)

```
-spec ringback_endpoint_id(kapps_call:call()) -> kz_term:api_binary().
ringback_endpoint_id(Call) ->
    case kapps_call:restricted_endpoint_id(Call) of
        undefined ->
            kapps_call:authorizing_id(Call);
        EndpointId ->
            lager:debug("call was referred by endpoint id  => ~s / ~s", [kapps_call:account_id(Call), EndpointId]),
            EndpointId
    end.
```

**Comment by lazedo** [comment]
@icehess the description and the code mismatch

**Comment by icehess** [comment]
oops, i messed up two different tickets, closing this, will create a new pr with change requested

**Pull request closed without merging**
